//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiFGRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Push
    {
        public int idFaculdade { get; set; }
        public string Nome { get; set; }
        public string Curso { get; set; }
        public string Periodo { get; set; }
        public string Turno { get; set; }
        public string Semestre { get; set; }
        public string Menssagem { get; set; }
    }
}
